name: 'icon_pack_flutter'
description: 'Icon Pack FLutter For Help You Add Icon For Your Application'
version: '0.0.1'
repository: 'https://github.com/azkadev/icon_pack_flutter'
homepage: 'https://github.com/azkadev/icon_pack_flutter'
documentation: 'https://github.com/azkadev/icon_pack_flutter'
issue_tracker: 'https://github.com/azkadev/icon_pack_flutter/issues'
funding:
  - "https://github.com/sponsors/azkadev"
  - "https://www.patreon.com/c/azkadev"
  - "https://opencollective.com/azkadev"
  - "https://paypal.me/azkaaxeliongibran"
  - "https://paypal.me/azkadev"
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=1.17.0'
dependencies:
  flutter:
    sdk: 'flutter'
  flutter_svg: ^2.2.1
dev_dependencies:
  flutter_lints: '^5.0.0'
  flutter_test:
    sdk: 'flutter'
flutter:
  assets:
    - 'assets/azkadev_icon_pack/bold/'
    - 'assets/azkadev_icon_pack/broken/'
    - 'assets/azkadev_icon_pack/bulk/'
    - 'assets/azkadev_icon_pack/linear/'
    - 'assets/azkadev_icon_pack/outline/'
    - 'assets/azkadev_icon_pack/twotone/'
  fonts: []
project:
  type: ''
  is_use_direct_package: false
  is_private: false
  developers:
    - username: ''
      note: ''
      social_medias:
        - 'https://github.com'
dependency_overrides:
  camera_android_camerax: '0.6.15'
  http:
    path: '../../../../.pub-cache/hosted/pub.dev/http-1.3.0'
  mime: '^2.0.0'
  path_provider_android: '2.2.17'
  pointycastle: '^4.0.0'
funding: []
