name: 'icon_pack_flutter'
description: 'A new Flutter package project.'
version: '0.0.1'
homepage: null
environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=1.17.0'
dependencies:
  flutter:
    sdk: 'flutter'
  flutter_svg: ^2.2.1
dev_dependencies:
  flutter_lints: '^5.0.0'
  flutter_test:
    sdk: 'flutter'
flutter:
  assets:
    - 'assets/azkadev_icon_pack/bold/'
    - 'assets/azkadev_icon_pack/broken/'
    - 'assets/azkadev_icon_pack/bulk/'
    - 'assets/azkadev_icon_pack/linear/'
    - 'assets/azkadev_icon_pack/outline/'
    - 'assets/azkadev_icon_pack/twotone/'
  fonts: []
project:
  type: ''
  is_use_direct_package: false
  is_private: false
  developers:
    - username: ''
      note: ''
      social_medias:
        - 'https://github.com'
dependency_overrides:
  camera_android_camerax: '0.6.15'
  http:
    path: '../../../../.pub-cache/hosted/pub.dev/http-1.3.0'
  mime: '^2.0.0'
  path_provider_android: '2.2.17'
  pointycastle: '^4.0.0'
funding: []
